version: '3.2'
services:
  postgres-database:
    image: postgres 
    restart: always
    networks: 
      - database 
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: PharmacyDatabase
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./scripts/fill_tables.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"

  pharmacy:
    image: jelenahrnjak/pharmacy:latest
    depends_on:
      - postgres-database
      - rabbitmq
    environment: 
      DATABASE_HOST: postgres-database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: PharmacyDatabase
      DATABASE_PASSWORD: admin
      DATABASE_USER: postgres
      RABBITMQ_HOST: "rabbitmq" 
      
    ports:
      - "8081:1026" 
    restart: on-failure
    networks:
      - application
      - database

  manager-front:
    depends_on:
      - pharmacy
    #build: ../ManagerFrontApp 
    image: jelenahrnjak/managerfrontapp:latest
    ports:
      - "4202:4200"
    restart: on-failure
    networks:
      - public
      - application

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
volumes:
  database-data:

networks:
  public:
    driver: bridge
  application:
    driver: bridge
  database:
    driver: bridge